enum SERVER_EVENTS {
  UPDATE_ROOM_CONFIG = 'UPDATE_ROOM_CONFIG',
  TICK = 'TICK',
  PLAYER_LANE_CHANGE = 'PLAYER_LANE_CHANGE',
  GAME_START = 'GAME_START',
  UPDATE_LEADERBOARD = 'UPDATE_LEADERBOARD',
  EJECTION = 'EJECTION',
  EJECTION_END = 'EJECTION_END',
  COLLISION = 'COLLISION',
  GAME_STOP = 'STOP',
}

enum CLIENT_EVENTS {
  JOIN_ROOM = 'JOIN_ROOM',
  READY = 'READY',
  INPUT_LANE_CHANGE = 'INPUT_LANE_CHANGE',
  PLAYER_TICK = 'PLAYER_TICK',
  PLAYER_COLLISION = 'PLAYER_COLLISION',
}

export { SERVER_EVENTS, CLIENT_EVENTS };
